_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 791f782f-9ec7-4cd9-ad24-7d74a70a2cd9
name: buildtoods-test
mail: alejandro.moreno@tdo.es
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
